ALTER TABLE STOCKS
    ADD COLUMN PRICE_CHANGE_RATIO float8 NOT NULL DEFAULT 0.0;

CREATE SEQUENCE STOCK_INDEX_VALUES_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE TABLE STOCK_INDEX_VALUES
(
    ID        bigint DEFAULT NEXTVAL('STOCK_INDEX_VALUES_SEQUENCE') PRIMARY KEY,
    TIMESTAMP timestamp NOT NULL,
    VALUE     decimal NOT NULL,
    STOCK_ID  bigint NOT NULL,
    FOREIGN KEY (STOCK_ID) REFERENCES STOCKS (ID)
);
