CREATE SEQUENCE TAGS_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE TABLE TAGS
(
    ID         bigint DEFAULT NEXTVAL('TAGS_SEQUENCE') PRIMARY KEY,
    NAME       varchar(255) unique NOT NULL
);

INSERT INTO TAGS (NAME) VALUES ('DEFAULT');

ALTER TABLE USERS
    ADD COLUMN TAG_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE USERS ADD CONSTRAINT USERS_TAG_FKEY
    FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID);

ALTER TABLE STOCKS
    ADD COLUMN TAG_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE STOCKS ADD CONSTRAINT STOCKS_TAG_FKEY
    FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID);
