CREATE SEQUENCE TAGS_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE TABLE TAGS
(
    ID         bigint DEFAULT NEXTVAL('TAGS_SEQUENCE') PRIMARY KEY,
    NAME       varchar(255) unique NOT NULL
);

INSERT INTO TAGS (NAME) VALUES ('DEFAULT');

ALTER TABLE USERS
    ADD COLUMN TAG_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE USERS ADD CONSTRAINT USERS_TAG_FKEY
    FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID) ON DELETE CASCADE;

ALTER TABLE RESOURCES DROP CONSTRAINT RESOURCES_USER_ID_FKEY;
ALTER TABLE RESOURCES ADD CONSTRAINT RESOURCES_USER_ID_FKEY
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;

ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_USER_ID_FKEY;
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_USER_ID_FKEY
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;

ALTER TABLE ARCHIVED_ORDERS ADD CONSTRAINT ARCHIVED_ORDERS_USER_ID_FKEY
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;

ALTER TABLE STOCKS
    ADD COLUMN TAG_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE STOCKS ADD CONSTRAINT STOCKS_TAG_FKEY
    FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID) ON DELETE CASCADE;

ALTER TABLE RESOURCES DROP CONSTRAINT RESOURCES_STOCK_ID_FKEY;
ALTER TABLE RESOURCES ADD CONSTRAINT RESOURCES_STOCK_ID_FKEY
    FOREIGN KEY (STOCK_ID) REFERENCES STOCKS(ID) ON DELETE CASCADE;

ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_STOCK_ID_FKEY;
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_STOCK_ID_FKEY
    FOREIGN KEY (STOCK_ID) REFERENCES STOCKS(ID) ON DELETE CASCADE;

ALTER TABLE ARCHIVED_ORDERS ADD CONSTRAINT ARCHIVED_ORDERS_STOCK_ID_FKEY
    FOREIGN KEY (STOCK_ID) REFERENCES STOCKS(ID) ON DELETE CASCADE;

ALTER TABLE STOCK_INDEX_VALUES DROP CONSTRAINT STOCK_INDEX_VALUES_STOCK_ID_FKEY;
ALTER TABLE STOCK_INDEX_VALUES ADD CONSTRAINT STOCK_INDEX_VALUES_STOCK_ID_FKEY
    FOREIGN KEY (STOCK_ID) REFERENCES STOCKS(ID) ON DELETE CASCADE;

ALTER TABLE TRANSACTIONS DROP CONSTRAINT TRANSACTIONS_BUYING_ORDER_ID_FKEY;
ALTER TABLE TRANSACTIONS ADD CONSTRAINT TRANSACTIONS_BUYING_ORDER_ID_FKEY
    FOREIGN KEY (BUYING_ORDER_ID) REFERENCES ARCHIVED_ORDERS(ID) ON DELETE CASCADE;

ALTER TABLE TRANSACTIONS DROP CONSTRAINT TRANSACTIONS_SELLING_ORDER_ID_FKEY;
ALTER TABLE TRANSACTIONS ADD CONSTRAINT TRANSACTIONS_SELLING_ORDER_ID_FKEY
    FOREIGN KEY (SELLING_ORDER_ID) REFERENCES ARCHIVED_ORDERS(ID) ON DELETE CASCADE;
