CREATE SEQUENCE SYSTEM_RESOURCES_MONITOR_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE TABLE SYSTEM_RESOURCES_MONITOR
(
    ID            bigint DEFAULT NEXTVAL('SYSTEM_RESOURCES_MONITOR_SEQUENCE') PRIMARY KEY,
    TIMESTAMP     timestamp NOT NULL,
    CPU_USAGE     double precision   NOT NULL,
    MEMORY_USAGE  double precision   NOT NULL,
    MEMORY_USED   bigint    NOT NULL
);
